# Generated by Django 2.2.17 on 2020-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='otu',
        ),
        migrations.AddField(
            model_name='post',
            name='microorganism',
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
    ]
