# Generated by Django 2.2.17 on 2020-12-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201206_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='microorganism',
            field=models.CharField(max_length=50),
        ),
    ]
